### ISSUE TITLE
Test failures with the development version of igraph

### ISSUE THREAD

**Issue by krlmlr** [sachsmc/causaloptim#18]
We're changing the layout of igraph objects. This leads to check failures in your package, see https://github.com/igraph/rigraph/blob/f-igraph-t-idx-revdepcheck/revdep/problems.md and https://github.com/igraph/rigraph/pull/789 for details.

To reproduce, please install the development version of igraph via

```r
# install.packages("pak")
pak::pak("igraph/rigraph")
```

and run `R CMD check` on your package.

We plan to release an igraph update on June 12, three weeks from now. Can you please send an update to CRAN that fixes the checks, or tell me that the failure is unexpected and we should be fixing this?

(~~We will replace the segfault with a clean error, but the~~ The symptoms are now different than shown in the linked document. The `"dag input 2"` test needs to use `new.env(parent = emptyenv())` instead of `"<environment>"` either way. I haven't looked further.)

**Comment by krlmlr** [comment]
These issues might now be resolved, I couldn't replicate the failures. Still, `structure(... "<environment>" ...)` looks a bit shady.

**Comment by sachsmc** [comment]
@krlmlr Thanks for the heads up. I agree it is shady, that was the result of using dput to replicate some user input to be tested. I will rework it so that the igraph object is created in a not shady way and then send to CRAN. I'll let you know when that happens.
